### ISSUE TITLE
iambic setup encounters pydantic.error_wrappers.ValidationError: 1 validation error for AWSOrganization

### ISSUE THREAD

**Issue by smoy** [noqdev/iambic#298]
iambic version: 0.1.186

```
(env) smoy@smoy-mba noq-dev-iambic % pip freeze | grep iambic
iambic-core==0.1.186
```

I encounter the following exception during `iambic setup` when I use temporary credentials from AWS SSO

```
Traceback (most recent call last):
  File "/Users/smoy/github/noq-dev-iambic/env/bin/iambic", line 8, in <module>
    sys.exit(cli())
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/iambic/main.py", line 458, in setup
    ConfigurationWizard(repo_dir).run()
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/iambic/config/wizard.py", line 1716, in run
    self.configuration_wizard_aws()
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/iambic/config/wizard.py", line 1101, in configuration_wizard_aws
    self.configuration_wizard_aws_organizations()
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/iambic/config/wizard.py", line 1088, in configuration_wizard_aws_organizations
    self.configuration_wizard_aws_organizations_add()
  File "/Users/smoy/github/noq-dev-iambic/env/lib/python3.10/site-packages/iambic/config/wizard.py", line 1029, in configuration_wizard_aws_organizations_add
    aws_org = AWSOrganization(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AWSOrganization
region
  extra fields not permitted (type=value_error.extra)
```

**Comment by smoy** [comment]
this is fixed by https://github.com/noqdev/iambic/pull/299
