### ISSUE TITLE
IAMbic fail to import a AWS ManagedPolicy that uses a dictionary statement instead of list of statements

### ISSUE THREAD

**Issue by smoy** [noqdev/iambic#397]
**Describe the bug**
```
error=ValidationError(model='ManagedPolicyProperties', errors=[{'loc': ('PolicyDocument',), 'msg': 'value is not a valid dict', 'type': 'type_error.dict'}, {'loc': ('PolicyDocument', 1, 'Statement'), 'msg': 'value is not a valid list', 'type': 'type_error.list'}])
```

minimum policy document to trigger the bug

```
{
    "Version": "2012-10-17",
    "Statement": {
        "Sid": "VisualEditor0",
        "Effect": "Allow",
        "Action": "sts:GetCallerIdentity",
        "Resource": "*"
    }
}
```

**To Reproduce**

**Expected behavior**
It should work since its from an import from AWS environment

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by shreyasdamle** [comment]
Thanks for the call today. I'm looking forward to use iambic. Here's the stack trace relating to a problem I encountered while importing:
```
Traceback (most recent call last):
  File "/Users/shreyasdamle/git/iambic-templates/venv/bin/iambic", line 8, in <module>
    sys.exit(cli())
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/main.py", line 405, in import_
    asyncio.run(config.run_import(exe_message, repo_dir))
  File "/Users/shreyasdamle/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/shreyasdamle/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/config/dynamic_config.py", line 232, in run_import
    await asyncio.gather(*tasks)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/handlers.py", line 433, in import_aws_resources
    await asyncio.gather(*tasks)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/handlers.py", line 316, in import_service_resources
    await asyncio.gather(
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/iam/policy/template_generation.py", line 478, in generate_aws_managed_policy_templates
    resource_template = await create_templated_managed_policy(
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/iam/policy/template_generation.py", line 300, in create_templated_managed_policy
    ManagedPolicyProperties(**template_properties),
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/core/models.py", line 84, in __init__
    super().__init__(*args, **kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for ManagedPolicyProperties
PolicyDocument
  value is not a valid dict (type=type_error.dict)
PolicyDocument -> 1 -> Statement
  value is not a valid list (type=type_error.list)
```

**Comment by smoy** [comment]
We have included a fix in version 0.7.3

Because pypi typically does not fetch a new version if it's just a maintenance update. You may need to install it via 

`pip install iambic-core==0.7.3` if you already have 0.7.1 installed.

The fix is reflected in PR https://github.com/noqdev/iambic/pull/398

**Comment by smoy** [comment]
@shreyasdamle Let us know if version 0.7.3 resolved your issue. Let us know if have run into any other issues. Cheers.

**Comment by shreyasdamle** [comment]
@smoy Getting a similar issue for `resource_id` now:
```
Traceback (most recent call last):
  File "/Users/shreyasdamle/git/iambic-templates/venv/bin/iambic", line 8, in <module>
    sys.exit(cli())
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/main.py", line 405, in import_
    asyncio.run(config.run_import(exe_message, repo_dir))
  File "/Users/shreyasdamle/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/shreyasdamle/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/config/dynamic_config.py", line 232, in run_import
    await asyncio.gather(*tasks)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/handlers.py", line 433, in import_aws_resources
    await asyncio.gather(*tasks)
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/handlers.py", line 316, in import_service_resources
    await asyncio.gather(
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/iam/role/template_generation.py", line 589, in generate_aws_role_templates
    resource_template = await create_templated_role(
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/plugins/v0_1_0/aws/iam/role/template_generation.py", line 413, in create_templated_role
    return create_or_update_template(
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/core/template_generation.py", line 555, in create_or_update_template
    merged_template = merge_model(
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/core/template_generation.py", line 1015, in merge_model
    merge_model(new_value, existing_value, all_provider_children),
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/core/template_generation.py", line 993, in merge_model
    new_value = merge_access_model_list(
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/core/template_generation.py", line 766, in merge_access_model_list
    matching_existing_models = [
  File "/Users/shreyasdamle/git/iambic-templates/venv/lib/python3.9/site-packages/iambic/core/template_generation.py", line 769, in <listcomp>
    if (existing_model.resource_id == new_model.resource_id)
AttributeError: 'int' object has no attribute 'resource_id'
```
