### ISSUE TITLE
`iambic setup`: "Setup AWS change detection" fails with `'ConfigurationWizard' object has no attribute 'hub_account_id'`

### ISSUE THREAD

**Issue by datfinesoul** [noqdev/iambic#407]
**Describe the bug**

**To Reproduce**
1. Use iambic 0.7.5
2. Logged in with valid admin credentials in the AWS management account
3. After having setup the organization, running `iambic setup` again
4. Choose "Setup AWS change detection"
5. Answer "Y" to both prompts
6. Error appears

**Expected behavior**
No error

**Screenshots**
```text
→ iambic setup
2023/05/13 06:09:17 [info     ] IAMBIC_DOCKER_CONTAINER is set, using /app as writable directory
2023/05/13 06:09:17 [info     ] Found existing configuration file 
  config_path=/templates/iambic_config.yaml
2023/05/13 06:09:17 [info     ] Loading config...
2023/05/13 06:09:17 [info     ] Setting config metadata...
2023/05/13 06:09:21 [info     ] Plugins loaded successfully...
? What would you like to configure? Setup AWS change detection

This requires that you have the ability to create CloudFormation stacks, stack sets, and stack set instances.
If you are using an AWS Organization, be sure that trusted access is enabled.
You can check this using the AWS Console:
  https://ap-northeast-1.console.aws.amazon.com/organizations/v2/home/services/CloudFormation%20StackSets
? Proceed? Yes
2023/05/13 06:09:33 [info     ] IAMbic change detection relies on CloudTrail being enabled all IAMbic aware accounts. You can check that you have CloudTrail setup by going to https://ap-northeast-1.console.aws.amazon.com/cloudtrail/home
If you do not have CloudTrail setup, you can set it up by going to https://ap-northeast-1.console.aws.amazon.com/cloudtrail/home?region=ap-northeast-1#/create

To setup change detection for iambic it requires creating CloudFormation stacks and a CloudFormation stack set.
To review the templates used or deploy them manually, the IdentityRule templates used can be found here:
https://github.com/noqdev/iambic/tree/main/iambic/plugins/v0_1_0/aws/cloud_formation/templates
If you have already manually deployed the templates, answer yes to proceed.
IAMbic will validate that your stacks have been deployed successfully and will not attempt to replace them.
? Proceed? Yes
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/iambic/main.py", line 491, in <module>
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/iambic/main.py", line 475, in setup
    ConfigurationWizard(repo_dir, is_more_options=is_more_options).run()
  File "/app/iambic/config/wizard.py", line 1960, in run
    self.configuration_wizard_change_detection_setup(
  File "/app/iambic/config/wizard.py", line 1849, in configuration_wizard_change_detection_setup
    session, _ = self.get_boto3_session_for_account(aws_org.org_account_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/iambic/config/wizard.py", line 628, in get_boto3_session_for_account
    if account_id == self.hub_account_id:
                     ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigurationWizard' object has no attribute 'hub_account_id'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 0.7.5

**Comment by castrapel** [comment]
@datfinesoul  can you share the IAMbic configuration? (It's okay to filter out parameters). I went through this process yesterday but I set up an AWS organization and change detection in a single execution of `iambic setup`. I will also give it a go with separate executions.
