### ISSUE TITLE
Hub_Role_stack_Name

### ISSUE THREAD

**Issue by mxw-sec** [noqdev/iambic#412]
**Describe the bug**
Attempting to add a 2nd AWS Account to an existing IAMBIC configuration

`Traceback (most recent call last):
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/bin/iambic", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/iambic/main.py", line 475, in setup
    ConfigurationWizard(repo_dir, is_more_options=is_more_options).run()
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/iambic/config/wizard.py", line 1933, in run
    self.configuration_wizard_aws()
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/iambic/config/wizard.py", line 1302, in configuration_wizard_aws
    self.configuration_wizard_aws_accounts()
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/iambic/config/wizard.py", line 1103, in configuration_wizard_aws_accounts
    self.configuration_wizard_aws_account_add()
  File "/Users/michael.woodside/repos/devops-iambic-controls/venv/lib/python3.11/site-packages/iambic/config/wizard.py", line 914, in configuration_wizard_aws_account_add
    create_spoke_role_stack(
TypeError: create_spoke_role_stack() got an unexpected keyword argument 'hub_role_stack_name'`

**To Reproduce**
Launch iambic setup, select AWS, then AWS accounts.

next in the wizard select add AWS account, and provide the details of the Identity, Account #, name, region, and finally the Role ARN (Optional). 

select proceed then crash

**Expected behavior**
Spoke role be created for accessing the 2nd account from the primary hub account. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS M2 v13.3
- Version -- Latest Release

**Comment by mxw-sec** [comment]
Also every time the setup fails, it appends the Hub account information to the variables section over and over and over again.

**Comment by mxw-sec** [comment]
Was able to manually create a SpokeRole and add the account to the configuration as a work around.

**Comment by Will-NOQ** [comment]
Thanks for letting us know, we'll start looking into this ASAP.
