### ISSUE TITLE
Directory Extension on AD Synced Group Causing Error

### ISSUE THREAD

**Issue by sprkyco** [noqdev/iambic#423]
**Describe the bug**
When importing Azure AD group error encountered regarding unexpected field. 

```
Traceback (most recent call last):
  File "/Users/sparkywood/miniconda3/envs/iambic/bin/iambic", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/workbench/iambic/iambic/main.py", line 406, in import_
    asyncio.run(config.run_import(exe_message, repo_dir))
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/miniconda3/envs/iambic/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/sparkywood/workbench/iambic/iambic/config/dynamic_config.py", line 232, in run_import
    await asyncio.gather(*tasks)
  File "/Users/sparkywood/workbench/iambic/iambic/plugins/v0_1_0/azure_ad/handlers.py", line 65, in import_azure_ad_resources
    await asyncio.gather(*collector_tasks)
  File "/Users/sparkywood/workbench/iambic/iambic/plugins/v0_1_0/azure_ad/group/template_generation.py", line 61, in collect_org_groups
    groups = await list_groups(azure_organization)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/workbench/iambic/iambic/plugins/v0_1_0/azure_ad/group/utils.py", line 97, in list_groups
    groups = [GroupTemplateProperties.from_azure_response(g) for g in groups]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/workbench/iambic/iambic/plugins/v0_1_0/azure_ad/group/utils.py", line 97, in <listcomp>
    groups = [GroupTemplateProperties.from_azure_response(g) for g in groups]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sparkywood/workbench/iambic/iambic/plugins/v0_1_0/azure_ad/group/models.py", line 219, in from_azure_response
    return cls(
           ^^^^
  File "/Users/sparkywood/workbench/iambic/iambic/plugins/v0_1_0/azure_ad/group/models.py", line 197, in __init__
    super().__init__(**data)
  File "/Users/sparkywood/workbench/iambic/iambic/core/models.py", line 84, in __init__
    super().__init__(*args, **kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GroupTemplateProperties
extension_08bfb2ea400b4328805e4a0221abff48_s_amaccount_name
  extra fields not permitted (type=value_error.extra)
```

**To Reproduce**

1. Environment is using Azure AD sync to sync user/groups from on-premise Acitve Directory
2. When using this pattern directory extensions are added to groups for dynamic group membership (reference: https://learn.microsoft.com/en-us/azure/active-directory/hybrid/connect/how-to-connect-sync-feature-directory-extensions)
3. When this occurs groups may have extension fields on them like `extension_08bfb2ea40deadb33ff48_s_amaccount_name`
4. After setting up Azure AD creds for iambic run iambic import
5. Error will occur on any group with directory extension

**Expected behavior**
iambic should ignore these fields as they are not a feature available to iambic

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.

**Comment by Will-NOQ** [comment]
Thanks for letting us know! I'll start looking into this now

**Comment by castrapel** [comment]
@sprkyco - Would you mind testing this PR for us to see if it resolves the issue: https://github.com/noqdev/iambic/pull/424

**Comment by castrapel** [comment]
This should be fixed and merged, but please re-open if you're still having trouble! I tested by creating a schema extension with custom attributes to replicate the problem, then performed an import to verify functionality.
