### ISSUE TITLE
IAMbic in docker crashes since 0.7.17

### ISSUE THREAD

**Issue by datfinesoul** [noqdev/iambic#426]
**Describe the bug**
Up until `iambic` 0.7.16 I was able to run iambic in a docker container using an alias.

```bash
docker run -it -u 1001:1001 -v /home/datfinesoul/.aws:/app/.aws:ro -e AWS_CONFIG_FILE=/app/.aws/config -e AWS_SHARED_CREDENTIALS_FILE=/app/.aws/credentials -e AWS_PROFILE -e HOME=/app -v /home/datfinesoul/github/undefined-io/iambic-templates:/templates:Z public.ecr.aws/iambic/iambic:0.7.16
```
```text
Unable to find image 'public.ecr.aws/iambic/iambic:0.7.16' locally
0.7.16: Pulling from iambic/iambic
044c2e2e5f7c: Already exists 
9a5f39b6f74b: Already exists 
5b52d63ce717: Already exists 
5454bc441089: Already exists 
06b9c4d322ba: Already exists 
d477b118eba2: Already exists 
d9c69844924e: Already exists 
c0b9a7c8267e: Already exists 
4f4fb700ef54: Pull complete 
b714b12a3a87: Pull complete 
d67c8cdacbcd: Pull complete 
bc52b3ea96bd: Pull complete 
6666f084a238: Pull complete 
5210fd4eccc8: Pull complete 
93af40e90805: Pull complete 
133da388c909: Pull complete 
9a2eb3717ff5: Pull complete 
260a2a5ea3d6: Pull complete 
690f9dff2eed: Pull complete 
7c9eacad76df: Pull complete 
2024a80f1cde: Pull complete 
Digest: sha256:0002a1bd3cc7e4ff6c55f585fb9cee56a986d4747b41096fabf901b3fa77da07
Status: Downloaded newer image for public.ecr.aws/iambic/iambic:0.7.16
2023/05/24 06:11:40 [info     ] IAMBIC_DOCKER_CONTAINER is set, using /app as writable directory
Usage: python -m iambic.main [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  apply
  clone-repos
  config-discovery
  convert           Convert a string from AWS PascalCase JSON to IAMbic...
  detect
  expire
  import
  init
  lint
  plan
  setup
```

In both `iambic` 0.7.17 and  0.7.18 I get the following error:

```bash
docker run -it -u 1001:1001 -v /home/datfinesoul/.aws:/app/.aws:ro -e AWS_CONFIG_FILE=/app/.aws/config -e AWS_SHARED_CREDENTIALS_FILE=/app/.aws/credentials -e AWS_PROFILE -e HOME=/app -v /home/datfinesoul/github/undefined-io/iambic-templates:/templates:Z public.ecr.aws/iambic/iambic:0.7.18
```

```text
Unable to find image 'public.ecr.aws/iambic/iambic:0.7.18' locally
0.7.18: Pulling from iambic/iambic
Digest: sha256:59010ba9a6a626d14652c43e8835eae0de5810d344a8530590c3ce449423960c
Status: Downloaded newer image for public.ecr.aws/iambic/iambic:0.7.18
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/iambic/main.py", line 19, in <module>
    from iambic.config.wizard import ConfigurationWizard
  File "/app/iambic/config/wizard.py", line 87, in <module>
    from iambic.plugins.v0_1_0.okta.iambic_plugin import OktaConfig, OktaOrganization
  File "/app/iambic/plugins/v0_1_0/okta/iambic_plugin.py", line 5, in <module>
    from okta.client import Client as OktaClient
  File "/usr/local/lib/python3.11/site-packages/okta/client.py", line 25, in <module>
    from okta.request_executor import RequestExecutor
  File "/usr/local/lib/python3.11/site-packages/okta/request_executor.py", line 5, in <module>
    from okta.api_response import OktaAPIResponse
  File "/usr/local/lib/python3.11/site-packages/okta/api_response.py", line 3, in <module>
    from okta.api_client import APIClient
  File "/usr/local/lib/python3.11/site-packages/okta/api_client.py", line 1, in <module>
    from pydash.strings import camel_case
  File "/usr/local/lib/python3.11/site-packages/pydash/__init__.py", line 170, in <module>
    from .objects import (
  File "/usr/local/lib/python3.11/site-packages/pydash/objects.py", line 17, in <module>
    from .utilities import PathToken, to_path, to_path_tokens
  File "/usr/local/lib/python3.11/site-packages/pydash/utilities.py", line 577, in <module>
    class MemoizedFunc(Protocol[P, T, T2]):
                       ~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.11/typing.py", line 344, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/typing_extensions.py", line 672, in __class_getitem__
    raise TypeError(
TypeError: Parameters to Protocol[...] must all be type variables. Parameter 1 is ~P
```

**To Reproduce**
See above

**Expected behavior**
The app should not crash

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Ubuntu 22.04
- Browser [e.g. chrome, safari] Chrome, Firefox
- Version [e.g. 22] 0.7.18

**Additional context**

**Community Engagement**
Your vote counts! Please support this bug report by adding a 👍 reaction to the original issue, which will aid the community and maintainers in addressing this problem.

Please refrain from adding "+1" or "me too" comments, as these create unnecessary noise for issue followers and do not help in prioritizing the issue. If you wish to contribute to solving this issue or have submitted a pull request, please leave a comment.

**Comment by Will-NOQ** [comment]
It looks like the issue was an unlocked dependency had released a new version that introduced some breaking changes. I went ahead and pinned the dependency to a working version and everything looks to be good now. 

The fix can be found in [this PR](https://github.com/noqdev/iambic/pull/427) for anyone curious. 

If you're using a virtual environment, running this command will fix the problem:
`pip install --upgrade typing-extensions`
